// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[PrimaryKey("OrderID", "ProductID")]
public partial class Order_Detail
{
    [Key]
    public int OrderID { get; set; }

    [Key]
    public int ProductID { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? UnitPrice { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("Order_Details")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Order_Details")]
    public virtual Product Product { get; set; }
}